services:
    api:
      build: ./spotify
      environment:
        - DB_HOST=db
        - DB_PORT=3306
      ports:
        - "8000:3000"
      restart: "unless-stopped"
      depends_on:
        - db
    db:
      image: mysql
      volumes:
        - ./my_spotify_db.sql:/docker-entrypoint-initdb.d/dump.sql
        - ./data/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=spotify
        - MYSQL_USER=spoty
        - MYSQL_PASSWORD=spotypwd
